apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obligatoriofe
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
  tls:
    hosts:
      - host
    secretName: secret
  rules:
  - host: host
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: obligatoriofe
              port:
                number: 80
