apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obligatoriofe
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
  tls:
    - hosts:
        - $(SERVICE_NAME).us-east-1.elb.amazonaws.com
      secretName: secret
  rules:
    - host: $(SERVICE_NAME).us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecr-demo-obli  # Nombre del Service que deseas exponer
                port:
                  number: 80
